export const ACCOUNTING_CALLABLE_NAMES = {
  upsertFinancialConfig: 'accountingUpsertFinancialConfig',
  setCreditCommissionRule: 'accountingSetCreditCommissionRule',
  upsertSalaryConfiguration: 'accountingUpsertSalaryConfiguration',
  upsertPayrollConfig: 'accountingUpsertPayrollConfig',
  generateCuota: 'accountingGenerateCuota',
  registerPayment: 'accountingRegisterPayment',
  registerMemberFeeBatchPayment: 'accountingRegisterMemberFeeBatchPayment',
  reconcileMemberFeeRenewals: 'accountingReconcileMemberFeeRenewals',
  createInstallmentPlan: 'accountingCreateInstallmentPlan',
  registerInstallmentPayment: 'accountingRegisterInstallmentPayment',
  listMyReceipts: 'accountingListMyReceipts',
  transferFunds: 'accountingTransferFunds',
  editInternalTransfer: 'accountingEditInternalTransfer',
  createHandicapCharge: 'accountingCreateHandicapCharge',
  transferHandicapToAssociation: 'accountingTransferHandicapToAssociation',
  transferPendingHandicapToAssociation: 'accountingTransferPendingHandicapToAssociation',
  registerExpenseMovement: 'accountingRegisterExpenseMovement',
  submitExpense: 'accountingSubmitExpense',
  reviewExpense: 'accountingReviewExpense',
  postExpenseMovement: 'accountingPostExpenseMovement',
  recordExternalReference: 'accountingRecordExternalReference',
  upsertEmployeeExternalReference: 'accountingUpsertEmployeeExternalReference',
  createOvertimeEntry: 'accountingCreateOvertimeEntry',
  reviewOvertimeEntry: 'accountingReviewOvertimeEntry',
  listEmployeePayrollCycle: 'accountingListEmployeePayrollCycle',
  postEmployeePayrollCycle: 'accountingPostEmployeePayrollCycle',
  postAnnualBonusPayment: 'accountingPostAnnualBonusPayment',
  recordEmployeeCertificate: 'accountingRecordEmployeeCertificate',
  linkExternalReferenceToEmployee: 'accountingLinkExternalReferenceToEmployee',
  createCashClosure: 'accountingCreateCashClosure',
  closeCashClosure: 'accountingCloseCashClosure',
  markMembershipRenewals: 'accountingMarkMembershipRenewals',
  reconcileMacroSettlement: 'accountingReconcileMacroSettlement',
  voidFinancialMovement: 'accountingVoidFinancialMovement',
  editFinancialMovement: 'accountingEditFinancialMovement',
  setFinancialMovementBalanceInclusion: 'accountingSetFinancialMovementBalanceInclusion',
} as const;

export const ACCOUNTING_COLLECTIONS = {
  financialConfigs: 'financial_configs',
  paymentMethods: 'payment_methods',
  paymentCommissionRules: 'payment_commission_rules',
  financialIncomeCategories: 'financial_income_categories',
  financialExpenseCategories: 'financial_expense_categories',
  financialMovements: 'financial_movements',
  macroDebitSettlements: 'macro_debit_settlements',
  expenseSubmissions: 'expense_submissions',
  salaryConfigurations: 'salary_configurations',
  salaryPayments: 'salary_payments',
  payrollConfigs: 'payroll_configs',
  externalAccountingReferences: 'external_accounting_references',
  employeeAccountingLinks: 'employee_accounting_links',
  employeeCertificates: 'employee_certificates',
  employeePayrollCycles: 'employee_payroll_cycles',
  overtimeEntries: 'overtime_entries',
  cashClosures: 'cash_closures',
  handicapCharges: 'handicap_charges',
  memberFeeCharges: 'member_fee_charges',
} as const;

export const ACCOUNTING_PAYMENT_METHOD_IDS = {
  debitMacro: 'debit_macro',
  transferMacro: 'transfer_macro',
  qrMacro: 'qr_macro',
  transferGalicia: 'transfer_galicia',
  qrGalicia: 'qr_galicia',
  debitGalicia: 'debit_galicia',
  creditGalicia: 'credit_galicia',
  debit: 'debit',
  transfer: 'transfer',
  credit: 'credit',
  cash: 'cash',
} as const;

export const ACCOUNTING_INCOME_CATEGORY_IDS = {
  cuotaSocietaria: 'cuota_societaria',
  greenFee: 'green_fee',
  tournamentRegistration: 'tournament_registration',
  rentalTennis: 'rental_tennis',
  rentalPadel: 'rental_padel',
  rentalGym: 'rental_gym',
  concessionCantinero: 'concession_cantinero',
  concessionMonthly: 'concession_monthly',
  advertisingBoard: 'advertising_board',
  advertisingAntenna: 'advertising_antenna',
  handicap: 'handicap',
  rentalHall: 'rental_hall',
  rentalGreenSpace: 'rental_green_space',
  internalTransfer: 'transferencia_interna_ingreso',
} as const;

export const ACCOUNTING_EXPENSE_CATEGORY_IDS = {
  sueldo: 'sueldo',
  f931: 'f931',
  obraSocial: 'obra_social',
  art: 'art',
  horasExtra: 'horas_extra',
  proveedores: 'proveedores',
  insumosAgropecuarios: 'insumos_agropecuarios',
  combustible: 'combustible',
  lubricantes: 'lubricantes',
  luz: 'luz',
  agua: 'agua',
  bancarios: 'bancarios',
  mantenimiento: 'mantenimiento',
  limpieza: 'limpieza',
  insumos: 'insumos',
  servidor: 'servidor',
  varios: 'varios',
  internalTransfer: 'transferencia_interna_egreso',
} as const;

export const ACCOUNTING_REFERENCE_TYPES = ['F931', 'OBRA_SOCIAL', 'ART', 'OTHER'] as const;

export function getAccountingReferenceTypeLabel(referenceType: (typeof ACCOUNTING_REFERENCE_TYPES)[number]) {
  return referenceType === 'OTHER' ? 'Otro' : referenceType;
}
