export const USERS_COLLECTIONS = {
    users: 'users',
    roles: 'roles',
    permissions: 'permissions',
    rolePermissions: 'role_permissions',
    memberTypes: 'member_types',
    familyGroups: 'family_groups',
    members: 'members',
    employees: 'employees',
    handicaps: 'handicaps',
    memberLoginIdentifiers: 'member_login_identifiers',
    passwordResetRequests: 'password_reset_requests',
};
export const SYSTEM_ACTOR_UID = 'system';
export const DEFAULT_PRIMARY_ROLE_ID = 'socio';
export const EXECUTIVE_COMMITTEE_ROLE_ID = 'comite_ejecutivo';
export const LEGACY_DIRECTIVO_ROLE_ID = 'directivo';
export const BOARD_COMMISSION_ROLE_ID = 'comision_directiva';
export const EXECUTIVE_ACCESS_ROLE_IDS = [EXECUTIVE_COMMITTEE_ROLE_ID, LEGACY_DIRECTIVO_ROLE_ID];
export const STAFF_ROLE_IDS = [EXECUTIVE_COMMITTEE_ROLE_ID, LEGACY_DIRECTIVO_ROLE_ID, 'administrativo'];
export const DEVELOPER_ROLE_ID = 'desarrollador';
export const INTERNAL_ROLE_IDS = [DEVELOPER_ROLE_ID];
export const CLAIM_ROLE_IDS = [
    EXECUTIVE_COMMITTEE_ROLE_ID,
    LEGACY_DIRECTIVO_ROLE_ID,
    'administrativo',
    'empleado',
    BOARD_COMMISSION_ROLE_ID,
    'socio',
    DEVELOPER_ROLE_ID,
];
export const PRIMARY_ROLE_PRECEDENCE = [
    EXECUTIVE_COMMITTEE_ROLE_ID,
    LEGACY_DIRECTIVO_ROLE_ID,
    'administrativo',
    'empleado',
    BOARD_COMMISSION_ROLE_ID,
    'socio',
    DEVELOPER_ROLE_ID,
];
export const MAX_LICENSE_MONTHS = 6;
export const MAX_FAMILY_GROUP_SIZE = 99;
export const MEMBER_TYPE_IDS = {
    pleno: 'pleno',
    vitalicio: 'vitalicio',
    menor: 'menor',
    licencia: 'licencia',
    grupoFamiliarAsociado: 'grupo_familiar_asociado',
    grupoFamiliarTitular: 'grupo_familiar_titular',
};
export const DEFAULT_ROLES = [
    {
        name: 'Comité Ejecutivo',
        description: 'Administra permisos, roles y decisiones sensibles del club.',
        permissionIds: ['users.roles.manage', 'users.members.manage', 'users.employees.manage', 'users.handicaps.manage'],
        system: true,
        active: true,
        sortOrder: 10,
    },
    {
        name: 'Directivo legado',
        description: 'Alias técnico de compatibilidad para usuarios creados antes de Comité Ejecutivo.',
        permissionIds: ['users.roles.manage', 'users.members.manage', 'users.employees.manage', 'users.handicaps.manage'],
        system: true,
        active: false,
        sortOrder: 15,
    },
    {
        name: 'Administrativo',
        description: 'Opera altas, bajas y mantenimiento administrativo.',
        permissionIds: ['users.members.manage', 'users.employees.manage', 'users.handicaps.manage'],
        system: true,
        active: true,
        sortOrder: 20,
    },
    {
        name: 'Empleado',
        description: 'Rol operativo para personal del club.',
        permissionIds: [],
        system: true,
        active: true,
        sortOrder: 30,
    },
    {
        name: 'Comisión Directiva',
        description: 'Cargo institucional visible para socios de comisión, sin permisos administrativos extra.',
        permissionIds: [],
        system: true,
        active: true,
        sortOrder: 35,
    },
    {
        name: 'Socio',
        description: 'Rol base para usuarios vinculados a un socio.',
        permissionIds: [],
        system: true,
        active: true,
        sortOrder: 40,
    },
];
export const DEFAULT_PERMISSIONS = [
    {
        id: 'users.roles.manage',
        module: 'users',
        action: 'roles.manage',
        name: 'Gestionar roles',
        description: 'Permite asignar y revocar roles de usuario.',
        active: true,
    },
    {
        id: 'users.members.manage',
        module: 'users',
        action: 'members.manage',
        name: 'Gestionar socios',
        description: 'Permite crear y modificar socios, grupos familiares y licencias.',
        active: true,
    },
    {
        id: 'users.employees.manage',
        module: 'users',
        action: 'employees.manage',
        name: 'Gestionar empleados',
        description: 'Permite crear y modificar empleados.',
        active: true,
    },
    {
        id: 'users.handicaps.manage',
        module: 'users',
        action: 'handicaps.manage',
        name: 'Gestionar handicap',
        description: 'Permite registrar y administrar handicap de socios.',
        active: true,
    },
];
export const DEFAULT_ROLE_PERMISSIONS = [
    {
        id: 'comite_ejecutivo__users.roles.manage',
        roleId: EXECUTIVE_COMMITTEE_ROLE_ID,
        permissionId: 'users.roles.manage',
        active: true,
        grantedByUid: SYSTEM_ACTOR_UID,
        grantedAt: null,
    },
    {
        id: 'comite_ejecutivo__users.members.manage',
        roleId: EXECUTIVE_COMMITTEE_ROLE_ID,
        permissionId: 'users.members.manage',
        active: true,
        grantedByUid: SYSTEM_ACTOR_UID,
        grantedAt: null,
    },
    {
        id: 'comite_ejecutivo__users.employees.manage',
        roleId: EXECUTIVE_COMMITTEE_ROLE_ID,
        permissionId: 'users.employees.manage',
        active: true,
        grantedByUid: SYSTEM_ACTOR_UID,
        grantedAt: null,
    },
    {
        id: 'comite_ejecutivo__users.handicaps.manage',
        roleId: EXECUTIVE_COMMITTEE_ROLE_ID,
        permissionId: 'users.handicaps.manage',
        active: true,
        grantedByUid: SYSTEM_ACTOR_UID,
        grantedAt: null,
    },
    {
        id: 'directivo__users.roles.manage',
        roleId: LEGACY_DIRECTIVO_ROLE_ID,
        permissionId: 'users.roles.manage',
        active: true,
        grantedByUid: SYSTEM_ACTOR_UID,
        grantedAt: null,
    },
    {
        id: 'directivo__users.members.manage',
        roleId: LEGACY_DIRECTIVO_ROLE_ID,
        permissionId: 'users.members.manage',
        active: true,
        grantedByUid: SYSTEM_ACTOR_UID,
        grantedAt: null,
    },
    {
        id: 'directivo__users.employees.manage',
        roleId: LEGACY_DIRECTIVO_ROLE_ID,
        permissionId: 'users.employees.manage',
        active: true,
        grantedByUid: SYSTEM_ACTOR_UID,
        grantedAt: null,
    },
    {
        id: 'directivo__users.handicaps.manage',
        roleId: LEGACY_DIRECTIVO_ROLE_ID,
        permissionId: 'users.handicaps.manage',
        active: true,
        grantedByUid: SYSTEM_ACTOR_UID,
        grantedAt: null,
    },
    {
        id: 'administrativo__users.members.manage',
        roleId: 'administrativo',
        permissionId: 'users.members.manage',
        active: true,
        grantedByUid: SYSTEM_ACTOR_UID,
        grantedAt: null,
    },
    {
        id: 'administrativo__users.employees.manage',
        roleId: 'administrativo',
        permissionId: 'users.employees.manage',
        active: true,
        grantedByUid: SYSTEM_ACTOR_UID,
        grantedAt: null,
    },
    {
        id: 'administrativo__users.handicaps.manage',
        roleId: 'administrativo',
        permissionId: 'users.handicaps.manage',
        active: true,
        grantedByUid: SYSTEM_ACTOR_UID,
        grantedAt: null,
    },
];
export const DEFAULT_MEMBER_TYPES = [
    {
        id: MEMBER_TYPE_IDS.pleno,
        label: 'Pleno',
        billingConfigKey: 'FULL',
        requiresFamilyGroup: false,
        canBeFamilyHolder: true,
        active: true,
        sortOrder: 10,
    },
    {
        id: MEMBER_TYPE_IDS.vitalicio,
        label: 'Vitalicio',
        billingConfigKey: 'LIFETIME',
        requiresFamilyGroup: false,
        canBeFamilyHolder: true,
        active: true,
        sortOrder: 20,
    },
    {
        id: MEMBER_TYPE_IDS.menor,
        label: 'Menor',
        billingConfigKey: 'MINOR',
        requiresFamilyGroup: false,
        canBeFamilyHolder: false,
        active: true,
        sortOrder: 30,
    },
    {
        id: MEMBER_TYPE_IDS.licencia,
        label: 'Licencia',
        billingConfigKey: 'LICENSE',
        requiresFamilyGroup: false,
        canBeFamilyHolder: false,
        active: true,
        sortOrder: 40,
    },
    {
        id: MEMBER_TYPE_IDS.grupoFamiliarAsociado,
        label: 'Grupo Familiar Asociado',
        billingConfigKey: 'FAMILY_ASSOC',
        requiresFamilyGroup: true,
        canBeFamilyHolder: false,
        active: true,
        sortOrder: 50,
    },
    {
        id: MEMBER_TYPE_IDS.grupoFamiliarTitular,
        label: 'Grupo Familiar Titular',
        billingConfigKey: 'FULL',
        requiresFamilyGroup: true,
        canBeFamilyHolder: true,
        active: true,
        sortOrder: 60,
    },
];
//# sourceMappingURL=constants.js.map